package main

import "fmt"

func main() {
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
	fmt.Println("MAIN")
}
